version: '3'

services:

    db:
        image: mariadb
        container_name: ButterflyKnife-DB
        hostname: db
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
            - ./my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: butterflyknife


    #server:
        #build: .
        #container_name: ButterflyKnife-Server
        #ports:
            #- "80:80"
        #volumes:
            #- "./server/server:/app"
